# Generated by Django 2.2 on 2020-05-13 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=100)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 5, 13, 15, 34, 59, 502665))),
            ],
        ),
    ]
