# Generated by Django 2.2 on 2020-05-19 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 13, 8, 55, 996670)),
        ),
    ]
