# Generated by Django 2.2 on 2020-05-19 14:27

import datetime
from django.db import migrations, models
import tea_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0004_auto_20200519_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 14, 27, 13, 630116)),
        ),
        migrations.AlterField(
            model_name='tea',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=tea_app.models.upload_path),
        ),
    ]
