# Generated by Django 2.2 on 2020-05-19 16:02

import datetime
from django.db import migrations, models
import tea_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0005_auto_20200519_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 16, 2, 4, 563303)),
        ),
        migrations.AlterField(
            model_name='tea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tea_app.models.upload_path),
        ),
    ]
